---
- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: Europe/Berlin
- name: Install open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present
    update_cache: yes
- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present
